Obeni/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField, SelectField, SubmitField, IntegerField, StringField, BooleanField
from wtforms.validators import Length, DataRequired, Email, EqualTo, Required




class LoginForm(FlaskForm):
    email = StringField('Email', validators=[Email(message='Incorrect Email Address!'), Required(), Length(min=5, max=32)])
    password = PasswordField('Password', validators=[Required(), Length(min=8, max=34)])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class ShippingForm(FlaskForm):
    firstname = TextField('First Name', validators=[DataRequired(), Length(min=3, max=20)])
    lastname = TextField('Last Name', validators=[Length(min=3, max=20)])
    email = TextField('Email', validators=[Email(message='This Field Requires a Valid Email Address'), DataRequired('Please Enter Your Email Address')])
    address = TextField('Address', validators=[DataRequired()])
    country = SelectField('Country', choices=['Nigeria','Ghana','Togo'])
    state = SelectField('State', choices=['Abia','Adamawa','Akwa-Ibom','Anambra','Bauchi','Bayelsa','Borno','Cross River', 'Delta','Ebonyi','Edo','Ekiti','Enugu','Gombe','Jigawa','Kaduna'], validators=[DataRequired()], default='Ekiti')
    city= TextField('City', validators=[DataRequired()])
    zipcode = TextField('Zip Code', validators=[DataRequired('Zipcode Required')])
    phone =  IntegerField('Phone Number', validators=[DataRequired(message='Please Include Your Phone Number')])

Obeni/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flask_admin import Admin, AdminIndexView
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from sqlalchemy import MetaData

## Database ##
convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


# db = SQLAlchemy(metadata=MetaData(naming_convention=convention))
db = SQLAlchemy()

## Mail ##
mail = Mail()

## Admin ##
admin = Admin(base_template='site-templates/admin_layout.html')

## Login and security ##
login_manager = LoginManager()
login_manager.login_view = 'main.login'
login_manager.login_message_category = 'info'

bcrypt = Bcrypt()

def register_extension(app):
    db.init_app(app)
    mail.init_app(app)
    admin.init_app(app, index_view=AdminIndexView(menu_icon_type='fa', menu_icon_value='tv',  name='Dashboard'))
    login_manager.init_app(app) 
    bcrypt.init_app(app)



def register_blueprint(app):
    from Obeni.main.routes import main
    from Obeni.admins.routes import admins

    app.register_blueprint(main)
    app.register_blueprint(admins)

    

def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    register_extension(app)
    register_blueprint(app)
    return app

Obeni/admins/routes.py
from flask import Blueprint, render_template
from flask_admin.contrib.sqla import ModelView

from Obeni import admin, db
from Obeni.model import Customer, Product, ProductAdminView, OrderView, Order


admins = Blueprint('admins', __name__)


admin.add_view(ModelView(Customer, db.session, menu_icon_type='fa', menu_icon_value='users'))
admin.add_view(ProductAdminView(Product, db.session, menu_icon_type='fa', menu_icon_value='box'))
# admin.add_view(OrderView())

Obeni/main/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, logout_user


from Obeni.forms import ShippingForm, LoginForm

main = Blueprint('main', __name__)



@main.route('/admin/logout/')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/admin/login/', methods=['POST','GET'])
def login():
    form = LoginForm()
    return render_template('admin/login.html', form=form)

@main.route('/checkout/')
def checkout():
    form = ShippingForm()
    return render_template('checkout.html', form=form)


@main.route('/cart/')
def cart():
    return render_template('cart.html')


@main.route('/product/')
def product():
    return render_template('product.html')

@main.route('/collection/')
def collection():
    return render_template('collection.html')

@main.route('/women/')
def women():
    return render_template('collection.html')


@main.route('/men/')
def men():
    return render_template('collection.html')

@main.route('/')
def index():
    return render_template('index.html')

Obeni/templates/cart.html
{% extends 'site-templates/layout.html' %}


{% block style %}
<style>
    .cart_styledSection {
        padding: 50px 0px;
    }
    .cart_styledShopTable {
        width: 100%;
    }
    .cart_styledShopTable tr:first-child {
        border-top: 1px solid #e1e1e1;
    }
    .cart_styledShopTable tr {
        border-bottom: 1px solid #e1e1e1;
        border-right: 1px solid #e1e1e1;
        border-left: 1px solid #e1e1e1;
        background-color: #fafafa;
    }
    .cart_styledShopTable th {
        padding-right: 19px;
    }
    .cart_styledShopTable td {
        text-align: right;
    }
    .cart_styledShopTable tr th,
    .cart_styledShopTable tr td  {
        padding: 15px 21px;
    }
    
    .table-centered tr {
        text-align: center;
        width: 100%;
    }
    .table-centered td {
        /* padding: 10px 5px; */
    }
</style>
{% endblock style %}

{% block body %}
<section>
    <div class="container-fluid">
        <div class="cart_styledSection">
            <div class="row">
                <div class="col-lg-6">
                    <form action="" method="post">
                        <h3>Shopping Cart</h3>
                        <table class="table-responsive table-centered" cellpadding="10">
                            <thead>
                                <tr>
                                    <th>Products</th>
                                    <th>Size</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="cart_styledProductThumbnail">
                                        <a href="#"><p><img src="" alt="">Cutaway Collar Double Cuff Fine Herrigngbone</p></a>
                                    </td>
                                    <td>
                                        M
                                    </td>
                                    <td class='cart_styledProductQuantity'>12,000</td>
                                    <td>
                                        <input type="number" name="" id="" style='width: 50px; text-align: center;' min="0" max="10" value='2'>
                                    </td>
                                    <td>12,000</td>
                                </tr>

                                <tr>
                                    <td class="cart_styledProductThumbnail">
                                        <a href="#">
                                            <p><img src="" alt="">Cutaway Collar Double Cuff Fine Herrigngbone</p>
                                        </a>
                                    </td>
                                    <td>
                                        M
                                    </td>
                                    <td class='cart_styledProductQuantity'>12,000</td>
                                    <td>2</td>
                                    <td>12,000</td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan='3' class='cart_styledActions'>
                                        <a href="{{ url_for('main.collection') }}" class="btn btn-outline">Continue Shopping</a>
                                        <button class="btn btn-outline">Update Cart</button>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </form>
                </div>
                <div class="col-lg-6">
                    <div class="cart_styledTotal">
                        <h2>Cart Total</h2>
                        <div class="cart_styledTable">
                            <table cellspacing='0' class='cart_styledShopTable'>
                                <tbody>
                                    <tr class="cart_styledSubTotal">
                                        <th>Subtotal</th>
                                        <td data-title="Subtotal">
                                            <span class='cart_styledPrice'>
                                                <span class="cart_styledCurrecyStmbol"></span>
                                                39,000.00
                                            </span>
                                        </td>
                                    </tr>
                                    <tr class="cart_styledShippingTotal">
                                        <th style="display: none;">Shipping</th>
                                        <td data-title='Shipping' colspan='2' style="text-align: left;">
                                            <p class="cart_styledShippingTitle">Shipping</p>
                                            <ul class="cart_styledShippingMethod">
                                                <label for="shipping_flat_rate">Flat Rate:</label>
                                                <span id="shipping_flat_rate">
                                                    <span class='cart_styledPrice'>
                                                        <span class="cart_styledCurrecyStmbol"></span>
                                                        1,500
                                                    </span>
                                                </span>
                                            </ul>
                                        </td>
                                    </tr>
                                    <tr class="cart_styledOrderTotal">
                                        <th>Total</th>
                                        <td data-title='Total'>
                                            <strong>
                                                <span class='cart_styledPrice'>
                                                    <span class="cart_styledCurrecyStmbol"></span>
                                                    39,000.00
                                                </span>
                                            </strong>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}

Obeni/templates/checkout.html
{% from 'site-templates/_macros.html' import render_field_with_errors, render_shortfield_with_errors %}

{% extends 'site-templates/layout.html' %}



{% block body %}
    <section>
        <div class="container">
            <div class="checkout_styledSection" style="padding-top: 40px;">
                <form action="" method="post">
                    <div class="row">
                        <div class="col-lg-6">
                            <div id="checkout_styledAddress">
                                <h3>Billing Details</h3>
                                <div class="formelement">
                                    <div class="form-row">
                                        {{ render_shortfield_with_errors(form.firstname) }}
                                        {{ render_shortfield_with_errors(form.lastname) }}
                                    </div>
                                    {{ render_field_with_errors(form.address) }}
                                    {{ render_field_with_errors(form.city) }}
                                    {{ render_field_with_errors(form.phone) }}
                                    {{ render_field_with_errors(form.email) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock body %}

Obeni/templates/collection.html
{% extends 'site-templates/layout.html' %}

{% block style %}
    <style>
        .collection_styledSection {
            padding: 40px 0px;
        }
    </style>
{% endblock style %}

{% block body %}
<section>
    <div class="container-fluid">
        <div class="collection_styledSection">
            <div class="row">
                <div class="col-lg-3">
                    <a href="#">
                        <div class="card">
                            <img src="{{ url_for('static', filename='images/Champion-T-Shirt.jpg') }}" alt="" class="card-img-top">
                            <div class="card-body">
                                <div class="card-title" style='text-align: center;'>
                                    <h5>Cutaway Collar Double Cuff Herringbone Shirt</h5>
                                    <p class="collection_styledColor">Navy Blue</p>
                                    <p class="collection_styledPrice">13,000</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="#">
                        <div class="card">
                            <img src="{{ url_for('static', filename='images/Champion-T-Shirt.jpg') }}" alt="" class="card-img-top">
                            <div class="card-body">
                                <div class="card-title" style="text-align: center;">
                                    <h5>Tank Top</h5>
                                    <p>OFF White</p>
                                    <p>&#8358; 15,000</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}

Obeni/templates/product.html
{% extends 'site-templates/layout.html' %}

{% block body %}
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">

            </div>
            <div class="col-lg-6">
                <h2>Product</h2>
                <h4>Price <span>$15000</span></h4>
                
            </div>
        </div>
    </div>
</section>
{% endblock body %}

Obeni/templates/site-templates/_macros.html
{% macro render_field_with_errors(field) %}
    {% if not field.errors %}
    <div class="form-group">
        <label for="{{ field.id }}"><strong>{{ field.label }}</strong></label>
        {{ field(class='form-control', **kwargs) | safe }}
    </div>
    {% else %}
    <div class="form-group">
        <label for="{{ field.id }}"><strong>{{ field.label }}</strong></label>
        {{ field(class='form-control is-invalid', **kwargs) | safe }}
        {% for error in field.errors %}
        <div id="{{ field.id }}" class='invalid-feedback'>
            {{ error }}
        </div>
        {% endfor %}
        
    </div>

    {% endif %}
{% endmacro %}


{% macro render_shortfield_with_errors(field) %}
    {% if not field.errors %}
    <div class="form-group col-md-6">
        <label for="{{ field.id }}"><strong>{{ field.label }}</strong></label>
        {{ field(class='form-control', **kwargs) | safe }}
    </div>
    {% else %}
    <div class="form-group col-md-6">
        <label for="{{ field.id }}"><strong>{{ field.label }}</strong></label>
        {{ field(class='form-control is-invalid', **kwargs) | safe }}
        {% for error in field.errors %}
        <div id="{{ field.id }}" class='invalid-feedback'>
            {{ error }}
        </div>
        {% endfor %}
        
    </div>

    {% endif %}


{% endmacro %}




{% macro render_sitem(endpoint, display, active='') %}
    <li {% if request.endpoint == endpoint or active == endpoint %} class='active nav-item' {% else %} class='nav-item' {% endif %}>
        <a class='nav-link' href="{{ url_for(endpoint) }}">{{ display }} <span class="sr-only">(current)</span></a>
    </li>
{% endmacro %}

Obeni/templates/site-templates/admin_layout.html
{% import 'admin/layout.html' as layout with context -%}
{% extends 'admin/base.html' %}

{% block head_tail %}
    {{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='plugins/font-awesome/css/all.css') }}">
<style>
    :root{
        --light-grey: #efefef;
        --dark-grey: #757272;
        --fz-xxs: 12px;
        --fz-xs: 13px;
        --fz-sm: 14px;
        --fz-md: 16px;
        --fz-lg: 18px;
        --fz-xl: 20px;
        --fz-heading: 32px;
        --transition: all 0.5s cubic-bezier(0.645,0.045,0.355,1);
        --blue-theme-1: #2a3042;
        --text-theme-1: #6a7187;
        --text-theme-2: #495057;
        --light-theme-1: #f8f8fb;
        --white: #fff;
        --darkest-theme-1: #292a2a;
        --dark-theme-1: #343a40; 
        --dark-theme-2: #313a46;
        --dark-theme-3: #313a46;
        --dark-theme-4: #37404a;
        --background-primary :#f8f9fe;
        --text-theme-1: #c8c8c8;
        --primary-color: #172b4d;
    }
    
    *,*::before,*::after{
        box-sizing: border-box;
        padding: 0px;
        margin: 0px;
    }
    body{
        font-family: sans-serif;
        color: #495057;
        margin: 0px !important;
        background-color: #fafbfe;
    }
    .h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
        color: #495057;
    }
    .table {
        width: 100%;
        color: #495057;
        vertical-align: top;
        border-color: #eff2f7;
    }
    
    .table .table-light {
        color: #495057;
        border-color: #eff2f7;
        background-color: #f8f9fa;
    }
    a, a:hover, a:active{
        text-decoration: none;
    }
    .badge-soft-success {
        color: #34c38f;
        background-color: rgba(52,195,143,.18);
    }
    .wrapper{
        min-height: 100vh;
        width: 100%;
        position: relative;
        color: #6c757d;
    }
    .left-side-menu {
        position: fixed;
        z-index: 5;
        top: 56px;
        bottom: 0;
        left: 0;
        width: 260px;
        background: var(--blue-theme-1);
        box-shadow: 0 0 35px 0 rgba(154,161,171,.15);
        transition: all .2s ease-out;
        padding-top: 70px;
    }
    .card {
        margin-bottom: 20px;
    }
    .left-side-menu ul.side-nav {
        list-style: none;
        font-size: 14px;
    }
    .left-side-menu ul li {
        /* background-color: var(--dark-theme-3); */
    }
    .left-side-menu ul li:hover {
        /* background-color: var(--dark-theme-2); */
    }
    .left-side-menu ul li:hover a, .left-side-menu ul li:hover i {
        color: var(--white);
    }
    .left-side-menu ul li a {
        color: var(--text-theme-1);
        padding: 20px 30px;
        display: inline-block;
        width: 100%;
    }
    .left-side-menu ul li i {
        margin-right: 10px;
        color: var(--text-theme-1);
    }
    .content-page{
        margin-left: 260px;
        padding: 90px 0px 0px 0 px;
        background-color: var(--light-theme-2);
        color: var(--text-theme-1);
    }
    
    .noti-icon{
        line-height: 70px !important;
        font-size: 22px;
    }
    .nav-user {
        padding: calc(31px / 2) 20px calc(31px / 2) 57px;
        display: flex;
        text-align: left;
        white-space: nowrap;
        background-color: #fafbfd;
        height: 100%;
        border-right: .25em solid transparent;
        border-left: .25em solid transparent;
        border-top: .25em solid;
    }
    @media (max-width: 1080px) { 
        .left-side-menu {
            width: 200px;
        }
        .content-page {
            margin-left: 200px;
        }
    }
    @media (max-width: 768px) {
        .left-side-menu {
            width: 200px;
            margin-left: -200px;
        }
        .content-page {
            margin-left: 0px;
        } 
    }
</style>
{% endblock %}




{% block page_body %}
    <div class="wrapper">
        <div class="root">
            <div class="dashboard_styledSection">
                <header>
                    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <a class="navbar-brand" href="/">Ogbeni</a>
                      
                        <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo03">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a href="#" class="nav-link"><i class="fa fa-search"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ url_for('main.cart') }}" class="nav-link"><i class="fa fa-shopping-cart"></i></a>
                                </li>
                              </ul>
                          <!-- <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                          </form> -->
                        </div>
                      </nav>
                </header>
            </div>
        </div>
        
            <div class="left-side-menu">
                <div id="left-side-menu-container" class="h-100">
                    <div class="side-menu-content">
                        <ul class="side-nav">
                            {{ layout.menu() }}
                            {{ layout.menu_links() }}
                            {% set render_ctx = h.resolve_ctx() %}
                            <li><a href="#"><i class="fa fa-wrench"></i>Settings</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="content-page">
                <div class="content">
                    
                    
                    <div class="container-fluid" style="padding-top: 80px">
                        
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="page-title-box">
                                    <h4>{{ admin_view.name | capitalize }}</h4>
                                </div>
                            </div>
                        </div>
                        {{ layout.messages() }}
                        {% block body %}
                        
                        {% endblock %}
                    </div>
                </div>
            </div>


            
            
            
    </div>
{% endblock %}

Obeni/templates/site-templates/layout.html
{% from 'site-templates/_macros.html' import render_sitem %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ogbeni Apparels</title>


    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }} ">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/font-awesome/css/all.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/bootstrap-4.5.3-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <style>
        :root {
            --light-grey: #efefef;
            --dark-grey: #757272;
            --fz-xxs: 12px;
            --fz-xs: 13px;
            --fz-sm: 14px;
            --fz-md: 16px;
            --fz-lg: 18px;
            --fz-xl: 20px;
            --fz-heading: 32px;
            --transition: all 0.5s cubic-bezier(0.645,0.045,0.355,1);;    
        }
        body {
            min-height: 100vh;
        }
        a, a:hover {
            text-decoration: none;
            color: #000;
        }
        section {
            min-height: calc(100vh - 400px);
            border-bottom: 2px solid var(--light-grey);
            padding: 50px 0px;
        }
        .btn-outline {
            border: 1px solid #000;
            transition: background-color .5s ease, color 1s ease;
            color: #000;
        }
        .btn-outline:hover {
            border: 1px solid #fff;
            color: #fff;
            background-color: #000;
        }
        
        .container_styledHeading {
            display: flex;
            width: 100%;
            -webkit-box-align: center;
            align-items: center;
            position: relative;
            margin: 10px 0px 40px;
            width: 100%;
            font-size: clamp(26px,5vw,var(--fz-heading));
            font-weight: bolder;
        }
        .container_styledHeading::after {
            position: relative;
            content: "";
            display: block;
            width: 100px;
            height: 3px;
            margin-left: 20px;
            background-color: var(--dark-grey);   
        }
        .footer_styledUpper {
            padding: 50px 0px;
            text-align: center;
        } 
        .footer_styledUpper ul {
            list-style: none;
            margin: 0;
            padding: 0;   
        }
        .footer_styledLower {
            color: var(--light-grey);
            background-color: black;
            padding: 80px 50px;
            display: flex;
            justify-content: space-between;
        }
        
    </style>

    {% block style %}

    {% endblock style %}
</head>
<body>
    <div class="wrapper">
        <div class="focus-wrapper">
            <div class="root">
                <header>
                    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <a class="navbar-brand" href="/">OGBENI</a>
                      
                        <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo03">
                            <ul class="navbar-nav">
                                {{ render_sitem('main.men', 'Men') }}
                                {{ render_sitem('main.women', 'Women') }}
                                {{ render_sitem('main.collection', 'Collection') }}
                                <li class="nav-item">
                                    <a href="#" class="nav-link"><i class="fa fa-search"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ url_for('main.cart') }}" class="nav-link"><i class="fa fa-shopping-cart"></i></a>
                                </li>
                              </ul>
                          <!-- <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                          </form> -->
                        </div>
                      </nav>
                </header>
                <div id="content">
                    <main>
                        {% block body %}
                        {% endblock body %}
                    </main>
                    <footer>
                        <div class="footer_styledUpper">
                            <div class="container">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <h3>Company</h3>
                                        <ul>
                                            <li><a href="#">Men</a></li>
                                            <li><a href="#">Women</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-3">
                                        <h3>Help</h3>
                                        <ul>
                                            <li><a href="#">Men</a></li>
                                            <li><a href="#">Women</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-3">
                                        <h3>Get Social</h3>
                                        <ul>
                                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-3">
                                        <h3>Contact</h3>
                                        <ul>
                                            <li><a href="#">Men</a></li>
                                            <li><a href="#">Women</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="footer_styledLower">
                            <p>Copyright 2021. All rights reserved</p>
                            <p>Ogbeni Apparels</p>
                        </div>
                    </footer>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/jquery-1.11.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='plugins/bootstrap-4.5.3-dist/js/bootstrap.min.js') }}"></script>
</body>
</html>